# Generated by Django 5.2.11 on 2026-02-24 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_autor_categoria_editora'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='autor',
            table='Autores',
        ),
    ]
