# Generated by Django 5.2.11 on 2026-03-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_autor_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editora',
            name='nome',
            field=models.CharField(max_length=10),
        ),
    ]
