# Generated by Django 5.2.11 on 2026-03-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_editora_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editora',
            name='descricao',
        ),
        migrations.AddField(
            model_name='editora',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
    ]
