# Generated by Django 5.2.11 on 2026-03-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_editora_descricao_editora_site'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.AlterField(
            model_name='editora',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='editora',
            name='site',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
